; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const POUND        ; 01
	const KARATE_CHOP  ; 02
	const DEFOG        ; 03
	const SHELL_SMASH  ; 04
	const FOUL_PLAY    ; 05
	const PAY_DAY      ; 06
	const FIRE_PUNCH   ; 07
	const ICE_PUNCH    ; 08
	const THUNDERPUNCH ; 09
	const LAVA_PLUME   ; 0a
	const SLUDGE_WAVE  ; 0b
	const LEAF_STORM   ; 0c
	const SUPERPOWER   ; 0d
	const SWORDS_DANCE ; 0e
	const CUT          ; 0f
	const CLEAR_SMOG   ; 10
	const WING_ATTACK  ; 11
	const WHIRLWIND    ; 12
	const FLY          ; 13
	const BIND         ; 14
	const VOLT_SWITCH  ; 15
	const STEALTH_ROCK ; 16
	const KNOCK_OFF    ; 17
	const DOUBLE_KICK  ; 18
	const FAKE_OUT     ; 19
	const JUMP_KICK    ; 1a
	const NASTY_PLOT   ; 1b
	const FREEZE_DRY   ; 1c
	const HEADBUTT     ; 1d
	const THROAT_CHOP  ; 1e
	const PLAY_ROUGH   ; 1f
	const AQUA_JET     ; 20
	const TACKLE       ; 21
	const BODY_SLAM    ; 22
	const WRAP         ; 23
	const FLARE_BLITZ  ; 24
	const THRASH       ; 25
	const DOUBLE_EDGE  ; 26
	const ACID_SPRAY   ; 27
	const HAMMER_ARM   ; 28
	const LEAF_BLADE   ; 29
	const PIN_MISSILE  ; 2a
	const DRAGON_PULSE ; 2b
	const HONE_CLAWS   ; 2c
	const HEX          ; 2d
	const ROAR         ; 2e
	const COSMIC_POWER ; 2f
	const DUAL_CHOP    ; 30
	const ICICLE_CRASH ; 31
	const DISABLE      ; 32
	const POWER_WHIP   ; 33
	const DRAIN_PUNCH  ; 34
	const FLAMETHROWER ; 35
	const MIST         ; 36
	const AURA_SPHERE  ; 37
	const HYDRO_PUMP   ; 38
	const SURF         ; 39
	const ICE_BEAM     ; 3a
	const BLIZZARD     ; 3b
	const PSYBEAM      ; 3c
	const BUBBLEBEAM   ; 3d
	const AURORA_BEAM  ; 3e
	const HYPER_BEAM   ; 3f
	const DAZLINGGLEAM ; 40
	const DRILL_PECK   ; 41
	const DARK_PULSE   ; 42
	const LOW_KICK     ; 43
	const COUNTER      ; 44
	const SEISMIC_TOSS ; 45
	const STRENGTH     ; 46
	const WILD_CHARGE  ; 47
	const FLASH_CANNON ; 48
	const LEECH_SEED   ; 49
	const GROWTH       ; 4a
	const ROCK_POLISH  ; 4b
	const SOLARBEAM    ; 4c
	const POISONPOWDER ; 4d
	const STUN_SPORE   ; 4e
	const SLEEP_POWDER ; 4f
	const PETAL_DANCE  ; 50
	const BULLDOZE     ; 51
	const OVERHEAT     ; 52
	const FIRE_SPIN    ; 53
	const HAIL         ; 54
	const THUNDERBOLT  ; 55
	const THUNDER_WAVE ; 56
	const THUNDER      ; 57
	const DRAGON_CLAW  ; 58
	const EARTHQUAKE   ; 59
	const DRAGON_TAIL  ; 5a
	const DIG          ; 5b
	const TOXIC        ; 5c
	const CROSS_POISON ; 5d
	const PSYCHIC_M    ; 5e
	const HYPNOSIS     ; 5f
	const IRON_HEAD    ; 60
	const AGILITY      ; 61
	const QUICK_ATTACK ; 62
	const RAGE         ; 63
	const TELEPORT     ; 64
	const NIGHT_SHADE  ; 65
	const MIMIC        ; 66
	const SCREECH      ; 67
	const FOCUS_BLAST  ; 68
	const RECOVER      ; 69
	const SHADOW_CLAW  ; 6a
	const MINIMIZE     ; 6b
	const COIL         ; 6c
	const CONFUSE_RAY  ; 6d
	const BRAVE_BIRD   ; 6e
	const DEFENSE_CURL ; 6f
	const BARRIER      ; 70
	const LIGHT_SCREEN ; 71
	const HAZE         ; 72
	const REFLECT      ; 73
	const FOCUS_ENERGY ; 74
	const BIDE         ; 75
	const METRONOME    ; 76
	const MIRROR_MOVE  ; 77
	const SELFDESTRUCT ; 78
	const GUNK_SHOT    ; 79
	const POWER_GEM    ; 7a
	const SEED_BOMB    ; 7b
	const SLUDGE       ; 7c
	const AQUA_TAIL    ; 7d
	const FIRE_BLAST   ; 7e
	const WATERFALL    ; 7f
	const CLAMP        ; 80
	const SWIFT        ; 81
	const SKULL_BASH   ; 82
	const HEAT_WAVE    ; 83
	const HYPER_VOICE  ; 84
	const AMNESIA      ; 85
	const HURRICANE    ; 86
	const SOFTBOILED   ; 87
	const HI_JUMP_KICK ; 88
	const GLARE        ; 89
	const DREAM_EATER  ; 8a
	const POISON_GAS   ; 8b
	const EXTRASENSORY ; 8c
	const LEECH_LIFE   ; 8d
	const LOVELY_KISS  ; 8e
	const SKY_ATTACK   ; 8f
	const TRANSFORM    ; 90
	const ZEN_HEADBUTT ; 91
	const DIZZY_PUNCH  ; 92
	const SPORE        ; 93
	const FLASH        ; 94
	const PSYWAVE      ; 95
	const MOONBLAST    ; 96
	const ACID_ARMOR   ; 97
	const CRABHAMMER   ; 98
	const EXPLOSION    ; 99
	const ICE_SHARD    ; 9a
	const BONEMERANG   ; 9b
	const REST         ; 9c
	const ROCK_SLIDE   ; 9d
	const HYPER_FANG   ; 9e
	const CALM_MIND    ; 9f
	const BULLET_PUNCH ; a0
	const TRI_ATTACK   ; a1
	const STONE_EDGE   ; a2
	const SLASH        ; a3
	const SUBSTITUTE   ; a4
	const STRUGGLE     ; a5
	const SKETCH       ; a6
	const BULK_UP      ; a7
	const THIEF        ; a8
	const SPIDER_WEB   ; a9
	const GYRO_BALL    ; aa
	const NIGHTMARE    ; ab
	const CLOSE_COMBAT ; ac
	const SNORE        ; ad
	const CURSE        ; ae
	const FLAIL        ; af
	const SCALD        ; b0
	const AEROBLAST    ; b1
	const STOCKPILE    ; b2
	const REVERSAL     ; b3
	const WILL_O_WISP  ; b4
	const EARTH_POWER  ; b5
	const PROTECT      ; b6
	const MACH_PUNCH   ; b7
	const SCARY_FACE   ; b8
	const FAINT_ATTACK ; b9
	const SHADOW_SNEAK ; ba
	const BELLY_DRUM   ; bb
	const SLUDGE_BOMB  ; bc
	const SUCKER_PUNCH ; bd
	const INFESTATION  ; be
	const SPIKES       ; bf
	const ZAP_CANNON   ; c0
	const ENERGY_BALL  ; c1
	const DESTINY_BOND ; c2
	const PERISH_SONG  ; c3
	const ICY_WIND     ; c4
	const DETECT       ; c5
	const BUG_BUZZ     ; c6
	const LIQUIDATION  ; c7
	const OUTRAGE      ; c8
	const SANDSTORM    ; c9
	const GIGA_DRAIN   ; ca
	const ENDURE       ; cb
	const CHARM        ; cc
	const ROLLOUT      ; cd
	const QUIVER_DANCE ; ce
	const SWAGGER      ; cf
	const MILK_DRINK   ; d0
	const DRILL_RUN    ; d1
	const FURY_CUTTER  ; d2
	const STEEL_WING   ; d3
	const MEAN_LOOK    ; d4
	const ATTRACT      ; d5
	const SLEEP_TALK   ; d6
	const HEAL_BELL    ; d7
	const RETURN       ; d8
	const PRESENT      ; d9
	const IRON_DEFENSE ; da
	const SAFEGUARD    ; db
	const PAIN_SPLIT   ; dc
	const SACRED_FIRE  ; dd
	const MAGNITUDE    ; de
	const BRICK_BREAK  ; df
	const MEGAHORN     ; e0
	const ACROBATICS   ; e1
	const BATON_PASS   ; e2
	const ENCORE       ; e3
	const PURSUIT      ; e4
	const RAPID_SPIN   ; e5
	const SWEET_SCENT  ; e6
	const IRON_TAIL    ; e7
	const ROOST        ; e8
	const U_TURN       ; e9
	const MORNING_SUN  ; ea
	const SYNTHESIS    ; eb
	const MOONLIGHT    ; ec
	const HIDDEN_POWER ; ed
	const CROSS_CHOP   ; ee
	const X_SCISSOR    ; ef
	const RAIN_DANCE   ; f0
	const SUNNY_DAY    ; f1
	const CRUNCH       ; f2
	const MIRROR_COAT  ; f3
	const DRAGON_DANCE ; f4
	const EXTREMESPEED ; f5
	const ANCIENTPOWER ; f6
	const SHADOW_BALL  ; f7
	const FUTURE_SIGHT ; f8
	const ROCK_SMASH   ; f9
	const WHIRLPOOL    ; fa
	const POISON_JAB   ; fb
	const SIGNAL_BEAM  ; fc
	const NIGHT_SLASH  ; fd
	const AIR_SLASH    ; fe
DEF NUM_ATTACKS EQU const_value - 1

; Battle animations use the same constants as the moves up to this point
	const_next $ff
	const ANIM_SWEET_SCENT_2     ; ff
	const ANIM_THROW_POKE_BALL   ; 100
	const ANIM_SEND_OUT_MON      ; 101
	const ANIM_RETURN_MON        ; 102
	const ANIM_CONFUSED          ; 103
	const ANIM_SLP               ; 104
	const ANIM_BRN               ; 105
	const ANIM_PSN               ; 106
	const ANIM_SAP               ; 107
	const ANIM_FRZ               ; 108
	const ANIM_PAR               ; 109
	const ANIM_IN_LOVE           ; 10a
	const ANIM_IN_SANDSTORM      ; 10b
	const ANIM_IN_NIGHTMARE      ; 10c
	const ANIM_IN_WHIRLPOOL      ; 10d
; battle anims
	const ANIM_MISS              ; 10e
	const ANIM_ENEMY_DAMAGE      ; 10f
	const ANIM_ENEMY_STAT_DOWN   ; 110
	const ANIM_PLAYER_STAT_DOWN  ; 111
	const ANIM_PLAYER_DAMAGE     ; 112
	const ANIM_WOBBLE            ; 113
	const ANIM_SHAKE             ; 114
	const ANIM_HIT_CONFUSION     ; 115
	const ANIM_IN_HAIL           ; 116
	const ANIM_IN_RAIN           ; 117
	const ANIM_IN_SUN            ; 118
DEF NUM_BATTLE_ANIMS EQU const_value - 1

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
